/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our Samples at https://docs.gradle.org/9.3.0/samples
 */
plugins {
    scala
    id("org.springframework.boot") version "3.2.0"
    id("io.spring.dependency-management") version "1.1.4"
}

group = "com.taskmanager"
version = "0.1.0"

java {
    sourceCompatibility = JavaVersion.VERSION_17
}

repositories {
    mavenCentral()
}

dependencies {
    implementation("org.springframework.boot:spring-boot-starter-web")
    implementation("org.springframework.boot:spring-boot-starter-data-jpa")
    implementation("org.scala-lang:scala3-library_3:3.3.1")
    implementation("com.fasterxml.jackson.module:jackson-module-scala_3:2.15.3")
    runtimeOnly("org.postgresql:postgresql")
    testImplementation("org.springframework.boot:spring-boot-starter-test")
    testImplementation("org.scalatest:scalatest_3:3.2.17")
    implementation("org.typelevel:cats_2.12:0.9.0")
    implementation("io.circe:circe-core_2.13:0.14.15")
}